version: '3'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: prueba_tecnica_db
    volumes:
      - trecesoftware:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_prueba_tecnica
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: prueba_tecnica@gmail.com
      PGADMIN_DEFAULT_PASSWORD: passdatabasepaulo
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  trecesoftware:
  pgadmin-data: